name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-nix

      - name: Check Nix formatting
        run: nix fmt -- --ci

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-nix

      - name: Run challenge tests as root
        run: |
          sudo nix run '.#challenges.tests'
