name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix (daemon, flakes)
        uses: cachix/install-nix-action@v31.5.2
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Show Nix version
        run: nix --version

      - name: Run challenge tests
        run: |
          nix run '.#challenges.tests'
