name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix (daemon, flakes)
        uses: cachix/install-nix-action@v31.5.2
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Nix
        run: |
          sudo ln -sf /nix/var/nix/profiles/default/bin/nix /usr/local/bin/nix

      - name: Show Nix version
        run: nix --version

      - name: Run challenge tests as root
        run: |
          sudo nix run '.#challenges.tests'
